### ISSUE TITLE
Initial item highlight is broken until first selection is made

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-matching#193]
### Subject of the issue
If using the keyboard up/down arrows, the item highlighting does not show until an initial selection is made.

Seems to have been introduced in https://github.com/adaptlearning/adapt-contrib-vanilla/pull/507

Where `.dropdown__btn.is-selected + ` is not valid until an initial selection.

**Comment by kirsty-hames** [comment]
Yep this is due to **Fix 2: Only apply selected styles when a dropdown item has been selected** of the above PR. If we revert the line above however, the issue still stands that there's no distinguish between the **selected** option and the **focused** option.

This is due to `aria-selected="true"` being applied to the **focused** option rather than the **selected** option only. 

To replicate, you can inspect the listbox `.dropdown__list` (expand so all `.dropdown-item`s are visible) in you devtools. In your course, navigate to the listbox via keyboard, select _enter_ to expand. Use _up/down arrows_ to navigate the options. As per the video below, `aria-selected="true"` chases the option with focus. In the video, I selected the last option '2015' prior to hitting record. I didn't make a selection during the video so `aria-selected="true"` should have remained on the last option.

https://github.com/user-attachments/assets/f6beeeb8-2ccc-4cbb-b538-18f5f08de6c1

Note, if no options are selected before the listbox receives focus, the first option receives focus. There's no requirement for an option to be automatically selected ([mdn listbox keyboard interactions for ref](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role#keyboard_interactions)).

I'll review this against https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/ as per #147

**Comment by oliverfoster** [comment]
Yes. It currently doesn't distinguish between highlighted/focused and selected. That is as designed. 

If I remember correctly, it was an issue with the placeholder text not being an acceptable entry in the list, such that once open it should not be possible to close the dropdown without making a valid selection.

Should it be able to be closed without making a selection? The should it return to the placeholder text, etc?

**Comment by kirsty-hames** [comment]
Please ignore my comment above @oliverfoster, this is separate to this issue and will address in #147. I'll raise a PR on Vanilla to address this issue.
